# Generated by Django 3.1.2 on 2020-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cities',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
